<?php

namespace ContainerSCSZixf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qmlhuw8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qmlhuw8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qmlhuw8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieArticle' => ['privates', '.errored..service_locator.Qmlhuw8.App\\Entity\\CategorieArticle', NULL, 'Cannot autowire service ".service_locator.Qmlhuw8": it references class "App\\Entity\\CategorieArticle" but no such service exists.'],
        ], [
            'categorieArticle' => 'App\\Entity\\CategorieArticle',
        ]);
    }
}
