<?php

namespace ContainerSCSZixf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NwdtbWmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NwdtbWm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NwdtbWm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieArticleRepository' => ['privates', 'App\\Repository\\CategorieArticleRepository', 'getCategorieArticleRepositoryService', true],
        ], [
            'categorieArticleRepository' => 'App\\Repository\\CategorieArticleRepository',
        ]);
    }
}
