<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CategorieArticle extends \App\Entity\CategorieArticle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'nom_cat_artic', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'date_ajout_artic', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'descriptif_artic', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'articles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'nom_cat_artic', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'date_ajout_artic', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'descriptif_artic', '' . "\0" . 'App\\Entity\\CategorieArticle' . "\0" . 'articles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CategorieArticle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCatArtic(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCatArtic', []);

        return parent::getNomCatArtic();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCatArtic(string $nom_cat_artic): \App\Entity\CategorieArticle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCatArtic', [$nom_cat_artic]);

        return parent::setNomCatArtic($nom_cat_artic);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjoutArtic(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjoutArtic', []);

        return parent::getDateAjoutArtic();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjoutArtic(\DateTimeInterface $date_ajout_artic): \App\Entity\CategorieArticle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjoutArtic', [$date_ajout_artic]);

        return parent::setDateAjoutArtic($date_ajout_artic);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptifArtic(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptifArtic', []);

        return parent::getDescriptifArtic();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptifArtic(string $descriptif_artic): \App\Entity\CategorieArticle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptifArtic', [$descriptif_artic]);

        return parent::setDescriptifArtic($descriptif_artic);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
