<?php

namespace ContainerEGpcb5a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FfLt4RYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FfLt4RY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FfLt4RY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieArticle' => ['privates', '.errored..service_locator.FfLt4RY.App\\Entity\\CategorieArticle', NULL, 'Cannot autowire service ".service_locator.FfLt4RY": it references class "App\\Entity\\CategorieArticle" but no such service exists.'],
            'categorieArticleRepository' => ['privates', 'App\\Repository\\CategorieArticleRepository', 'getCategorieArticleRepositoryService', true],
        ], [
            'categorieArticle' => 'App\\Entity\\CategorieArticle',
            'categorieArticleRepository' => 'App\\Repository\\CategorieArticleRepository',
        ]);
    }
}
