<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGpcb5a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGpcb5a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGpcb5a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGpcb5a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEGpcb5a\App_KernelDevDebugContainer([
    'container.build_hash' => 'EGpcb5a',
    'container.build_id' => 'd606df8c',
    'container.build_time' => 1682651092,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGpcb5a');
