<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_article_index' => [[], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['text', '/article/']], [], [], []],
    'app_article_indexFront' => [[], ['_controller' => 'App\\Controller\\ArticleController::indexFront'], [], [['text', '/article/lesarticles']], [], [], []],
    'app_article_new' => [[], ['_controller' => 'App\\Controller\\ArticleController::new'], [], [['text', '/article/new']], [], [], []],
    'app_article_show' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], [], []],
    'app_article_edit' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], [], []],
    'app_article_delete' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], [], []],
    'generator_service' => [[], ['_controller' => 'App\\Controller\\ArticleController::pdfEvenement'], [], [['text', '/article/pdf/evenement']], [], [], []],
    'app_categorie_article_index' => [[], ['_controller' => 'App\\Controller\\CategorieArticleController::index'], [], [['text', '/categorie/article/']], [], [], []],
    'app_categorie_article_new' => [[], ['_controller' => 'App\\Controller\\CategorieArticleController::new'], [], [['text', '/categorie/article/new']], [], [], []],
    'app_categorie_article_show' => [['id'], ['_controller' => 'App\\Controller\\CategorieArticleController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categorie/article']], [], [], []],
    'app_categorie_article_edit' => [['id'], ['_controller' => 'App\\Controller\\CategorieArticleController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categorie/article']], [], [], []],
    'app_categorie_article_delete' => [['id'], ['_controller' => 'App\\Controller\\CategorieArticleController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categorie/article']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
